version: '3.6'
services:
  sticker-convert:
    # image: sticker-convert # Uncomment for building locally
    # build: . # Uncomment for building locally
    image: laggykiller/sticker-convert:latest # Comment out for building locally
    volumes:
      - ./sticker_input:/app/stickers_input
      - ./sticker_output:/app/stickers_output
      # - ./creds.json:/app/creds.json
    ports:
      - 5800:5800 # Port for Web UI
      # - 5900:5900 # Optional for VNC
    tmpfs:
      - /tmp
    dns:
      - 1.1.1.1 # Or else download/upload to telegram fails in Docker
    # command: /usr/bin/python3 /app/main.py --help # Your command here