- module-name: 'py_mini_racer'
  dlls:
    - from_filenames:
        prefixes:
          - 'mini_racer'
      when: 'win32'
    - from_filenames:
        prefixes:
          - 'libmini_racer'
      when: 'not win32'
  data-files:
    patterns:
      - 'icudtl.dat'
      - 'snapshot_blob.bin'